#Studio Presence Automation Project
substitutions:
  name: studio-presence-sensor
  friendly_name: "Studio Presence Sensor"
  area: "Studio Room"
  version: "25.3.9"
  project_name: "NOTON COMICS.LD2410C-P Presence Sensor"
  device_description: ${name} for Presence Automation - v${version}.
  board: "nodemcu-32s"
  # Uncomment below line, if you're using ESP32 DevKit V1 board, then comment the previous line.
  #board: "esp32doit-devkit-v1"
  # Generate a 32-byte base64-encoded string or copy encryption key from [here](https://esphome.io/components/api.html#configuration-variables)
  api_encryption_key: "<REPLACE WITH API ENCRYPTION KEY HERE>"
  username: "<REPLACE WITH USERNAME>"
  password: "<REPLACE WITH PASSWORD>"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: " LD2410C-P Presence Sensor by NOTON COMICS"
  area: "${area}"

  project:
    name: "${project_name}"
    version: "${version}"

  min_version: 2025.5.2

esp32:
  board: "${board}"
  framework:
    type: arduino

# Enable logging
logger:

# Enable debug
debug:
  update_interval: 900s

# Enable Home Assistant API
api:
  encryption:
    key: "${api_encryption_key}"
  # Action for changing Bluetooth password of LD2410C (Home Assistant > Developer Tools > Actions > choose set_bluetooth_password action)
  actions:
    - action: set_bluetooth_password
      variables:
        password: string
      then:
        - bluetooth_password.set:
            id: ld2410_sensor
            password: !lambda "return password;"

ota:
  platform: esphome
  password: "${password}"

wifi:
  power_save_mode: none

  networks:
    - ssid: "<SET SSID 1>"
      password: "SET SSID 1 PASSWORD"
    - ssid: "SET SSID 2"
      password: "SET SSID 2 PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Studio Presence Sensor Hotspot"
    password: "<SET AP PASSWORD HERE>"

captive_portal:

#This is for LD2410 - Can be used with both ESP32 and ESP8266 Microcontrollers
# https://esphome.io/components/sensor/ld2410.html

web_server:
  version: 3
  port: 80
  local: true
  include_internal: true
  auth:
    username: "${username}"
    password: "${password}"
  sorting_groups:
    - id: sorting_group_occupancy
      name: "Presence/Occupancy Detection"
      sorting_weight: 10
    - id: sorting_group_energy_threshold
      name: "Zone Energy Threshold"
      sorting_weight: 40
    - id: sorting_group_distance
      name: "Presence Distance (cm)"
      sorting_weight: 20
    - id: sorting_group_energy
      name: "Presence Energy (%)"
      sorting_weight: 30
    - id: sorting_group_zone_configuration
      name: "Zone Configuration"
      sorting_weight: 90
    - id: sorting_group_sensor_diagnostic
      name: "Presence Sensor Diagnostic"
      sorting_weight: 99
    - id: sorting_group_esp_diagnostic
      name: "ESP Diagnostic"
      sorting_weight: 100

# ---------------------------------------------------------------------------------

uart:
  id: ld2410_uart
  tx_pin: GPIO14 # TX
  rx_pin: GPIO27 # RX
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_sensor

select:
  - platform: ld2410
    distance_resolution:
      name: Distance Resolution
      disabled_by_default: true
      internal: true
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic
    baud_rate:
      name: Baud Rate
      internal: true
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic
    light_function:
      name: Light Function
      internal: true
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic
    out_pin_level:
      name: Out Pin Level
      internal: true
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic

button:
  - platform: restart
    web_server:
      sorting_group_id: sorting_group_esp_diagnostic
    icon: mdi:restart
    name: "Reboot"
    internal: true

  - platform: factory_reset
    web_server:
      sorting_group_id: sorting_group_esp_diagnostic
    disabled_by_default: true
    name: "Factory Reset"
    id: factory_reset_all
    internal: true

  - platform: ld2410
    factory_reset:
      name: "Reset"
      internal: true
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic
    restart:
      name: "Restart"
      internal: true
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic
    query_params:
      name: "Query Params"
      internal: true
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic

number:
  - platform: ld2410
    timeout:
      name: Timeout
      mode: box
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic
    max_move_distance_gate:
      name: Max Move Distance Gate
      web_server:
        sorting_group_id: sorting_group_zone_configuration
    max_still_distance_gate:
      name: Max Still Distance Gate
      icon: mdi:leak
      web_server:
        sorting_group_id: sorting_group_zone_configuration
    g0:
      move_threshold:
        name: G0 Move Threshold
        web_server:
          sorting_group_id: sorting_group_energy_threshold
      still_threshold:
        name: G0 Still Threshold
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy_threshold
    g1:
      move_threshold:
        name: G1 Move Threshold
        web_server:
          sorting_group_id: sorting_group_energy_threshold
      still_threshold:
        name: G1 Still Threshold
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy_threshold
    g2:
      move_threshold:
        name: G2 Move Threshold
        web_server:
          sorting_group_id: sorting_group_energy_threshold
      still_threshold:
        name: G2 Still Threshold
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy_threshold
    g3:
      move_threshold:
        name: G3 Move Threshold
        web_server:
          sorting_group_id: sorting_group_energy_threshold
      still_threshold:
        name: G3 Still Threshold
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy_threshold
    g4:
      move_threshold:
        name: G4 Move Threshold
        web_server:
          sorting_group_id: sorting_group_energy_threshold
      still_threshold:
        name: G4 Still Threshold
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy_threshold
    g5:
      move_threshold:
        name: G5 Move Threshold
        web_server:
          sorting_group_id: sorting_group_energy_threshold
      still_threshold:
        name: G5 Still Threshold
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy_threshold
    g6:
      move_threshold:
        name: G6 Move Threshold
        web_server:
          sorting_group_id: sorting_group_energy_threshold
      still_threshold:
        name: G6 Still Threshold
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy_threshold
    g7:
      move_threshold:
        name: G7 Move Threshold
        web_server:
          sorting_group_id: sorting_group_energy_threshold
      still_threshold:
        name: G7 Still Threshold
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy_threshold
    g8:
      move_threshold:
        name: G8 Move Threshold
        web_server:
          sorting_group_id: sorting_group_energy_threshold
      still_threshold:
        name: G8 Still Threshold
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy_threshold
    light_threshold:
      name: Light Threshold
      web_server:
        sorting_group_id: sorting_group_energy_threshold

  # Setting start of zone 1 occupancy
  - platform: template
    web_server:
      sorting_group_id: sorting_group_zone_configuration
      sorting_weight: 10
    name: "Start Zone 1"
    id: ld2410_z1_start
    device_class: distance
    min_value: 0
    max_value: 800
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG
    unit_of_measurement: "cm"

  # Setting ending of zone 1 occupancy
  - platform: template
    web_server:
      sorting_group_id: sorting_group_zone_configuration
      sorting_weight: 20
    name: "End Zone 1"
    id: ld2410_z1_end
    device_class: distance
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 50
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG
    unit_of_measurement: "cm"

  # Setting ending of zone 2 occupancy
  - platform: template
    web_server:
      sorting_group_id: sorting_group_zone_configuration
      sorting_weight: 30
    name: "End Zone 2"
    id: ld2410_z2_end
    device_class: distance
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 150
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG
    unit_of_measurement: "cm"

  # Setting ending of zone 3 occupancy
  - platform: template
    web_server:
      sorting_group_id: sorting_group_zone_configuration
      sorting_weight: 40
    name: "End Zone 3"
    id: ld2410_z3_end
    device_class: distance
    min_value: 0
    max_value: 600
    step: 1
    mode: box
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 250
    icon: "mdi:arrow-collapse-right"
    entity_category: CONFIG
    unit_of_measurement: "cm"

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
      internal: true
      web_server:
        sorting_group_id: sorting_group_esp_diagnostic
    reset_reason:
      name: "Reset Reason"
      internal: true
      web_server:
        sorting_group_id: sorting_group_esp_diagnostic

  - platform: ld2410
    version:
      name: "Firmware Version"
      entity_category: "diagnostic"
      internal: true
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic
    mac_address:
      name: "Bluetooth MAC Address"
      icon: mdi:bluetooth-audio
      entity_category: "diagnostic"
      internal: true
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic
        sorting_weight: 20

  - platform: wifi_info
    ip_address:
      name: IP Address
      internal: true
      web_server:
        sorting_group_id: sorting_group_esp_diagnostic
    ssid:
      name: Connected SSID
      internal: true
      web_server:
        sorting_group_id: sorting_group_esp_diagnostic
    bssid:
      name: Connected BSSID
      internal: true
      web_server:
        sorting_group_id: sorting_group_esp_diagnostic
    mac_address:
      name: "MAC Address"
      icon: mdi:wan
      entity_category: "diagnostic"
      internal: true
      web_server:
        sorting_group_id: sorting_group_esp_diagnostic
    dns_address:
      name: "DNS Address"
      internal: true
      web_server:
        sorting_group_id: sorting_group_esp_diagnostic

switch:
  - platform: ld2410
    engineering_mode:
      name: "Engineering Mode"
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic
        sorting_weight: 30
    bluetooth:
      name: "Bluetooth"
      id: ld2410_bluetooth
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic
        sorting_weight: 10

sensor:
  # Uncomment below lines, if you need these debug info
  #  - platform: debug
  #    free:
  #      name: "Heap Free"
  #      web_server:
  #        sorting_group_id: sorting_group_esp_diagnostic
  #    block:
  #      name: "Heap Max Block"
  #      web_server:
  #        sorting_group_id: sorting_group_esp_diagnostic
  #    loop_time:
  #      name: "Loop Time"
  #      web_server:
  #        sorting_group_id: sorting_group_esp_diagnostic
  #    psram:
  #      name: "Free PSRAM"
  #      web_server:
  #        sorting_group_id: sorting_group_esp_diagnostic
  #    cpu_frequency:
  #      name: "CPU Frequency"
  #      web_server:
  #        sorting_group_id: sorting_group_esp_diagnostic

  - platform: internal_temperature
    web_server:
      sorting_group_id: sorting_group_esp_diagnostic
    name: "ESP Temperature"
    id: sys_esp_temperature
    icon: mdi:thermometer
    entity_category: "diagnostic"
    internal: true

  - platform: uptime
    web_server:
      sorting_group_id: sorting_group_esp_diagnostic
    name: Uptime
    id: sys_uptime
    update_interval: 60s
    entity_category: "diagnostic"
    internal: true

  - platform: wifi_signal
    web_server:
      sorting_group_id: sorting_group_esp_diagnostic
    name: WiFi Signal
    id: wifi_signal_db
    icon: mdi:signal-variant
    update_interval: 60s
    entity_category: "diagnostic"
    internal: true

  - platform: ld2410
    moving_distance:
      name: "Moving distance"
      id: moving_distance
      web_server:
        sorting_group_id: sorting_group_distance
    still_distance:
      name: "Still Distance"
      id: still_distance
      web_server:
        sorting_group_id: sorting_group_distance
    moving_energy:
      name: "Move Energy"
      id: move_energy
      web_server:
        sorting_group_id: sorting_group_energy
        sorting_weight: 5
    still_energy:
      name: "Still Energy"
      id: still_energy
      icon: mdi:leak
      web_server:
        sorting_group_id: sorting_group_energy
        sorting_weight: 5
    detection_distance:
      name: "Detection Distance"
      id: detection_distance
      web_server:
        sorting_group_id: sorting_group_distance

    g0:
      move_energy:
        name: G0 Move Energy
        web_server:
          sorting_group_id: sorting_group_energy
      still_energy:
        name: G0 Still Energy
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy
    g1:
      move_energy:
        name: G1 Move Energy
        web_server:
          sorting_group_id: sorting_group_energy
      still_energy:
        name: G1 Still Energy
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy
    g2:
      move_energy:
        name: G2 Move Energy
        web_server:
          sorting_group_id: sorting_group_energy
      still_energy:
        name: G2 Still Energy
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy
    g3:
      move_energy:
        name: G3 Move Energy
        web_server:
          sorting_group_id: sorting_group_energy
      still_energy:
        name: G3 Still Energy
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy
    g4:
      move_energy:
        name: G4 Move Energy
        web_server:
          sorting_group_id: sorting_group_energy
      still_energy:
        name: G4 Still Energy
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy
    g5:
      move_energy:
        name: G5 Move Energy
        web_server:
          sorting_group_id: sorting_group_energy
      still_energy:
        name: G5 Still Energy
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy
    g6:
      move_energy:
        name: G6 Move Energy
        web_server:
          sorting_group_id: sorting_group_energy
      still_energy:
        name: G6 Still Energy
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy
    g7:
      move_energy:
        name: G7 Move Energy
        web_server:
          sorting_group_id: sorting_group_energy
      still_energy:
        name: G7 Still Energy
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy
    g8:
      move_energy:
        name: G8 Move Energy
        web_server:
          sorting_group_id: sorting_group_energy
      still_energy:
        name: G8 Still Energy
        icon: mdi:leak
        web_server:
          sorting_group_id: sorting_group_energy
    light:
      name: "Ambient Light Energy"
      icon: mdi:brightness-6
      web_server:
        sorting_group_id: sorting_group_energy
        sorting_weight: 10

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      id: presence
      icon: mdi:home-sound-in
      device_class: presence
      web_server:
        sorting_group_id: sorting_group_occupancy
        sorting_weight: 10
    has_moving_target:
      name: Moving Target
      id: moving_target
      icon: mdi:motion-sensor
      device_class: motion
      web_server:
        sorting_group_id: sorting_group_occupancy
        sorting_weight: 20
    has_still_target:
      name: Still Target
      id: still_target
      icon: mdi:leak
      device_class: occupancy
      web_server:
        sorting_group_id: sorting_group_occupancy
        sorting_weight: 30
    out_pin_presence_status:
      name: Out Pin Presence Status (Engineering Mode)
      icon: mdi:square-wave
      internal: true
      web_server:
        sorting_group_id: sorting_group_sensor_diagnostic

  - platform: gpio
    pin: GPIO12
    name: Light Presence
    icon: mdi:wall-sconce-flat
    internal: true
    web_server:
      sorting_group_id: sorting_group_occupancy
      sorting_weight: 70

  ## Set Up Zones Based On Distance
  - platform: template
    name: "Zone 1 Occupancy"
    id: zone_1_occupancy
    device_class: occupancy
    icon: mdi:motion-sensor
    web_server:
      sorting_group_id: sorting_group_occupancy
      sorting_weight: 40
    lambda: |-
      if ((id(presence).state) && ((id(detection_distance).state <= id(ld2410_z1_end).state) && (id(detection_distance).state >= id(ld2410_z1_start).state))){
        return true;
      } else {
        return false;
      }
  - platform: template
    name: "Zone 2 Occupancy"
    id: zone_2_occupancy
    device_class: occupancy
    icon: mdi:motion-sensor
    web_server:
      sorting_group_id: sorting_group_occupancy
      sorting_weight: 50
    lambda: |-
      if ((id(presence).state) && ((id(ld2410_z1_end).state <= id(detection_distance).state) && (id(detection_distance).state <= id(ld2410_z2_end).state))) {
        return true;
      } else {
        return false;
      }
  - platform: template
    name: "Zone 3 Occupancy"
    id: zone_3_occupancy
    device_class: occupancy
    icon: mdi:motion-sensor
    web_server:
      sorting_group_id: sorting_group_occupancy
      sorting_weight: 60
    lambda: |-
      if ((id(presence).state) && ((id(ld2410_z2_end).state <= id(detection_distance).state) && (id(detection_distance).state <= id(ld2410_z3_end).state))) {
        return true;
      } else {
        return false;
      }